- name: Hello World Sample
  hosts: all
  tasks:
    - name: Ensure folder exists
      file:
        path: "keys"
        state: "directory"
    - name: pwd folder
      command:
        cmd: pwd && ls -l
    - name: Hello Message
      debug:
        msg: "Hello World!"

